v1.0.0
CodeGeeksInc/website pull request #1
Opened 2023-11-11 11:09 UTC by Hardikchhatbar2006

2023-11-27 07:57 UTC, AdiechaHK commented on Readme.txt
> +Hello, I'm doing this web project for my learning purposes...
please change this.

2023-11-27 07:58 UTC, AdiechaHK commented on Readme.txt
> +Hello, I'm doing this web project for my learning purposes...
this file should be `.md` file not `.txt` file.

2023-11-27 07:59 UTC, AdiechaHK commented on assets/scss/Readme.txt
> +The .scss (Sass) files are only available in the pro version.
this is also not needed.

2023-11-27 08:01 UTC, AdiechaHK commented on forms/contact.php
> +?>
This file is not needed at all.

2023-11-27 08:02 UTC, AdiechaHK requested changes
check my review

2023-11-27 10:45 UTC, Hardikchhatbar2006 commented
done

2023-11-27 14:54 UTC, AdiechaHK requested changes

2023-11-27 14:54 UTC, AdiechaHK commented on assets/js/main.js
> +  });
remove this if not needed

2023-11-27 14:54 UTC, AdiechaHK commented on assets/js/main.js
> +  new PureCounter();
remove if not needed

2023-11-28 05:08 UTC, Hardikchhatbar2006 commented on assets/js/main.js
> +  });
This is used in portfolio section too so it is mandatory

2023-11-28 05:19 UTC, Hardikchhatbar2006 commented on assets/js/main.js
> +  new PureCounter();
this is also needed for the counter that we have made by our logic

2023-11-28 06:34 UTC, AdiechaHK approved these changes

2023-11-28 06:34 UTC, merged